language: generic
env:
- MAX_OLD_SPACE_SIZE=1024

before_install:
- npm i serverless -g
- serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_KEY}

stages:
- Testing
- name: Deploy Dev
  if: branch = dev
- name: Deploy Prod
  if: branch = master

jobs: 
  include:
    - stage: Testing
      script:
      - echo "Running some test"
      - serverless version
    - stage:  Deploy Dev
      script: ./backend/deploy-dev.sh
    - stage:  Deploy Prod
      script: ./backend/deploy-prod.sh